source 'https://rubygems.org'

gem 'bcrypt-ruby'
gem 'blather'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'pg'
gem 'thin'
gem 'haml'
gem 'thinking-sphinx'
gem 'mysql2', '0.3.12b4'
gem 'will_paginate'